version: "3.8"

services:
  php:
    container_name: php
    build:
      context: ./etc/infraestructure/php
    ports:
      - '${PHP_PORT}:9000'
    volumes:
      - .:/var/www/${PROJECT_NAME}

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - .:/var/www/${PROJECT_NAME}
      - ./etc/infraestructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
